inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'db/migrate/**/*'
    - 'db/schema.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'app/controllers/swagger/**/*'

Metrics/MethodLength:
  Max: 7
  Exclude:
    - 'bin/bundle'
    - 'db/migrate/*'

Style/Documentation:
  Enabled: false